version: "3"
services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      POSTGRES_URL: postgres://postgres:mysecretpassword@db:5432/my_database
      POSTGRES_PRISMA_URL: postgres://postgres:mysecretpassword@db:5432/my_database?schema=public&connection_limit=1
      POSTGRES_URL_NON_POOLING: postgres://postgres:mysecretpassword@db:5432/my_database?pool=false
      AUTH_SECRET: 7da2aa8c73ed032e74dcf218bc0a8ed7

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: my_database
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
