export const usersData = [
  {
    username: "john_doe",
    email: "john.doe@example.com",
    password: "johndoe123",
    profile_image_url: "https://example.com/images/john.jpg",
  },
  {
    username: "jane_smith",
    email: "jane.smith@example.com",
    password: "janesmith123",
    profile_image_url: "https://example.com/images/jane.jpg",
  },
  {
    username: "mike_johnson",
    email: "mike.johnson@example.com",
    password: "mikejohnson123",
    profile_image_url: "https://example.com/images/mike.jpg",
  },
  {
    username: "emily_white",
    email: "emily.white@example.com",
    password: "emilywhite123",
    profile_image_url: "https://example.com/images/emily.jpg",
  },
  {
    username: "chris_brown",
    email: "chris.brown@example.com",
    password: "chrisbrown123",
    profile_image_url: "https://example.com/images/chris.jpg",
  },
  {
    username: "sophia_green",
    email: "sophia.green@example.com",
    password: "sophiagreen123",
    profile_image_url: "https://example.com/images/sophia.jpg",
  },
  {
    username: "david_martin",
    email: "david.martin@example.com",
    password: "davidmartin123",
    profile_image_url: "https://example.com/images/david.jpg",
  },
  {
    username: "linda_lee",
    email: "linda.lee@example.com",
    password: "lindalee123",
    profile_image_url: "https://example.com/images/linda.jpg",
  },
  {
    username: "paul_clark",
    email: "paul.clark@example.com",
    password: "paulclark123",
    profile_image_url: "https://example.com/images/paul.jpg",
  },
  {
    username: "nancy_hall",
    email: "nancy.hall@example.com",
    password: "nancyhall123",
    profile_image_url: "https://example.com/images/nancy.jpg",
  },
  {
    username: "kevin_james",
    email: "kevin.james@example.com",
    password: "kevinjames123",
    profile_image_url: "https://example.com/images/kevin.jpg",
  },
  {
    username: "laura_wilson",
    email: "laura.wilson@example.com",
    password: "laurawilson123",
    profile_image_url: "https://example.com/images/laura.jpg",
  },
  {
    username: "steven_moore",
    email: "steven.moore@example.com",
    password: "stevenmoore123",
    profile_image_url: "https://example.com/images/steven.jpg",
  },
  {
    username: "kimberly_brown",
    email: "kimberly.brown@example.com",
    password: "kimberlybrown123",
    profile_image_url: "https://example.com/images/kimberly.jpg",
  },
  {
    username: "jason_adams",
    email: "jason.adams@example.com",
    password: "jasonadams123",
    profile_image_url: "https://example.com/images/jason.jpg",
  },
  {
    username: "megan_turner",
    email: "megan.turner@example.com",
    password: "meganturner123",
    profile_image_url: "https://example.com/images/megan.jpg",
  },
  {
    username: "brian_jackson",
    email: "brian.jackson@example.com",
    password: "brianjackson123",
    profile_image_url: "https://example.com/images/brian.jpg",
  },
  {
    username: "rachel_martinez",
    email: "rachel.martinez@example.com",
    password: "rachelmartinez123",
    profile_image_url: "https://example.com/images/rachel.jpg",
  },
  {
    username: "andrew_garcia",
    email: "andrew.garcia@example.com",
    password: "andrewgarcia123",
    profile_image_url: "https://example.com/images/andrew.jpg",
  },
  {
    username: "lauren_rodriguez",
    email: "lauren.rodriguez@example.com",
    password: "laurenrodriguez123",
    profile_image_url: "https://example.com/images/lauren.jpg",
  },
  {
    username: "eric_anderson",
    email: "eric.anderson@example.com",
    password: "ericanderson123",
    profile_image_url: "https://example.com/images/eric.jpg",
  },
  {
    username: "olivia_thompson",
    email: "olivia.thompson@example.com",
    password: "oliviathompson123",
    profile_image_url: "https://example.com/images/olivia.jpg",
  },
  {
    username: "matthew_walker",
    email: "matthew.walker@example.com",
    password: "matthewwalker123",
    profile_image_url: "https://example.com/images/matthew.jpg",
  },
  {
    username: "samantha_white",
    email: "samantha.white@example.com",
    password: "samanthawhite123",
    profile_image_url: "https://example.com/images/samantha.jpg",
  },
  {
    username: "nicholas_harris",
    email: "nicholas.harris@example.com",
    password: "nicholasharris123",
    profile_image_url: "https://example.com/images/nicholas.jpg",
  },
  {
    username: "amber_young",
    email: "amber.young@example.com",
    password: "amberyoung123",
    profile_image_url: "https://example.com/images/amber.jpg",
  },
  {
    username: "robert_allen",
    email: "robert.allen@example.com",
    password: "robertallen123",
    profile_image_url: "https://example.com/images/robert.jpg",
  },
  {
    username: "elizabeth_king",
    email: "elizabeth.king@example.com",
    password: "elizabethking123",
    profile_image_url: "https://example.com/images/elizabeth.jpg",
  },
  {
    username: "patrick_scott",
    email: "patrick.scott@example.com",
    password: "patrickscott123",
    profile_image_url: "https://example.com/images/patrick.jpg",
  },
  {
    username: "danielle_hill",
    email: "danielle.hill@example.com",
    password: "daniellehill123",
    profile_image_url: "https://example.com/images/danielle.jpg",
  },
  {
    username: "jeffrey_lopez",
    email: "jeffrey.lopez@example.com",
    password: "jeffreylopez123",
    profile_image_url: "https://example.com/images/jeffrey.jpg",
  },
  {
    username: "sarah_hernandez",
    email: "sarah.hernandez@example.com",
    password: "sarahhernandez123",
    profile_image_url: "https://example.com/images/sarah.jpg",
  },
  {
    username: "joshua_wilson",
    email: "joshua.wilson@example.com",
    password: "joshuawilson123",
    profile_image_url: "https://example.com/images/joshua.jpg",
  },
  {
    username: "rebecca_richardson",
    email: "rebecca.richardson@example.com",
    password: "rebeccarichardson123",
    profile_image_url: "https://example.com/images/rebecca.jpg",
  },
  {
    username: "thomas_robinson",
    email: "thomas.robinson@example.com",
    password: "thomasrobinson123",
    profile_image_url: "https://example.com/images/thomas.jpg",
  },
  {
    username: "brandon_clark",
    email: "brandon.clark@example.com",
    password: "brandonclark123",
    profile_image_url: "https://example.com/images/brandon.jpg",
  },
  {
    username: "melissa_lewis",
    email: "melissa.lewis@example.com",
    password: "melissalewis123",
    profile_image_url: "https://example.com/images/melissa.jpg",
  },
  {
    username: "ethan_hall",
    email: "ethan.hall@example.com",
    password: "ethanhall123",
    profile_image_url: "https://example.com/images/ethan.jpg",
  },
  {
    username: "katherine_wright",
    email: "katherine.wright@example.com",
    password: "katherinewright123",
    profile_image_url: "https://example.com/images/katherine.jpg",
  },
  {
    username: "jake_perez",
    email: "jake.perez@example.com",
    password: "jakeperez123",
    profile_image_url: "https://example.com/images/jake.jpg",
  },
  {
    username: "victoria_roberts",
    email: "victoria.roberts@example.com",
    password: "victoriaroberts123",
    profile_image_url: "https://example.com/images/victoria.jpg",
  },
  {
    username: "jacob_taylor",
    email: "jacob.taylor@example.com",
    password: "jacobtaylor123",
    profile_image_url: "https://example.com/images/jacob.jpg",
  },
  {
    username: "allison_moore",
    email: "allison.moore@example.com",
    password: "allisonmoore123",
    profile_image_url: "https://example.com/images/allison.jpg",
  },
  {
    username: "ryan_lee",
    email: "ryan.lee@example.com",
    password: "ryanlee123",
    profile_image_url: "https://example.com/images/ryan.jpg",
  },
  {
    username: "michelle_jackson",
    email: "michelle.jackson@example.com",
    password: "michellejackson123",
    profile_image_url: "https://example.com/images/michelle.jpg",
  },
  {
    username: "zachary_walker",
    email: "zachary.walker@example.com",
    password: "zacharywalker123",
    profile_image_url: "https://example.com/images/zachary.jpg",
  },
  {
    username: "rachel_torres",
    email: "rachel.torres@example.com",
    password: "racheltorres123",
    profile_image_url: "https://example.com/images/rachel.jpg",
  },
  {
    username: "daniel_gonzalez",
    email: "daniel.gonzalez@example.com",
    password: "danielgonzalez123",
    profile_image_url: "https://example.com/images/daniel.jpg",
  },
  {
    username: "emma_hernandez",
    email: "emma.hernandez@example.com",
    password: "emmahernandez123",
    profile_image_url: "https://example.com/images/emma.jpg",
  },
  {
    username: "joshua_martin",
    email: "joshua.martin@example.com",
    password: "joshuamartin123",
    profile_image_url: "https://example.com/images/joshua.jpg",
  },
  {
    username: "ashley_lopez",
    email: "ashley.lopez@example.com",
    password: "ashleylopez123",
    profile_image_url: "https://example.com/images/ashley.jpg",
  },
  {
    username: "tyler_white",
    email: "tyler.white@example.com",
    password: "tylerwhite123",
    profile_image_url: "https://example.com/images/tyler.jpg",
  },
  {
    username: "hannah_miller",
    email: "hannah.miller@example.com",
    password: "hannahmiller123",
    profile_image_url: "https://example.com/images/hannah.jpg",
  },
  {
    username: "aaron_garcia",
    email: "aaron.garcia@example.com",
    password: "aarongarcia123",
    profile_image_url: "https://example.com/images/aaron.jpg",
  },
  {
    username: "sophia_anderson",
    email: "sophia.anderson@example.com",
    password: "sophiaanderson123",
    profile_image_url: "https://example.com/images/sophia.jpg",
  },
  {
    username: "elijah_martinez",
    email: "elijah.martinez@example.com",
    password: "elijahmartinez123",
    profile_image_url: "https://example.com/images/elijah.jpg",
  },
  {
    username: "megan_taylor",
    email: "megan.taylor@example.com",
    password: "megantaylor123",
    profile_image_url: "https://example.com/images/megan.jpg",
  },
  {
    username: "christopher_clark",
    email: "christopher.clark@example.com",
    password: "christopherclark123",
    profile_image_url: "https://example.com/images/christopher.jpg",
  },
  {
    username: "natalie_rodriguez",
    email: "natalie.rodriguez@example.com",
    password: "natalierodriguez123",
    profile_image_url: "https://example.com/images/natalie.jpg",
  },
  {
    username: "steven_wilson",
    email: "steven.wilson@example.com",
    password: "stevenwilson123",
    profile_image_url: "https://example.com/images/steven.jpg",
  },
  {
    username: "katie_harris",
    email: "katie.harris@example.com",
    password: "katieharris123",
    profile_image_url: "https://example.com/images/katie.jpg",
  },
  {
    username: "adam_jones",
    email: "adam.jones@example.com",
    password: "adamjones123",
    profile_image_url: "https://example.com/images/adam.jpg",
  },
  {
    username: "mia_scott",
    email: "mia.scott@example.com",
    password: "miascott123",
    profile_image_url: "https://example.com/images/mia.jpg",
  },
  {
    username: "nicholas_walker",
    email: "nicholas.walker@example.com",
    password: "nicholaswalker123",
    profile_image_url: "https://example.com/images/nicholas.jpg",
  },
  {
    username: "alyssa_perez",
    email: "alyssa.perez@example.com",
    password: "alyssaperez123",
    profile_image_url: "https://example.com/images/alyssa.jpg",
  },
  {
    username: "lucas_thompson",
    email: "lucas.thompson@example.com",
    password: "lucasthompson123",
    profile_image_url: "https://example.com/images/lucas.jpg",
  },
  {
    username: "madison_jackson",
    email: "madison.jackson@example.com",
    password: "madisonjackson123",
    profile_image_url: "https://example.com/images/madison.jpg",
  },
  {
    username: "andrew_lewis",
    email: "andrew.lewis@example.com",
    password: "andrewlewis123",
    profile_image_url: "https://example.com/images/andrew.jpg",
  },
];

export const offersData = [
  {
    user_id: 1,
    title: "Mountain Bike",
    description: "A slightly used mountain bike in excellent condition.",
    category: "Product",
    status: "available",
    image_url: "https://example.com/images/bike1.jpg",
    estimated_value: 300.0,
    created_at: "2024-10-01T10:00:00Z",
  },
  {
    user_id: 2,
    title: "Guitar Lessons",
    description:
      "Professional guitar lessons for beginners and advanced players.",
    category: "Service",
    status: "available",
    image_url: "https://example.com/images/guitar.jpg",
    estimated_value: 40.0,
    created_at: "2024-10-02T09:00:00Z",
  },
  {
    user_id: 3,
    title: "Coffee Maker",
    description: "Brand new coffee maker, still in box.",
    category: "Product",
    status: "available",
    image_url: "https://example.com/images/coffeemaker.jpg",
    estimated_value: 80.0,
    created_at: "2024-10-03T08:30:00Z",
  },
  {
    user_id: 4,
    title: "Yoga Classes",
    description: "Weekly yoga classes at your local studio.",
    category: "Service",
    status: "available",
    image_url: "https://example.com/images/yoga.jpg",
    estimated_value: 60.0,
    created_at: "2024-10-04T11:00:00Z",
  },
  {
    user_id: 5,
    title: "Smartphone",
    description: "Used smartphone in good condition, 128GB storage.",
    category: "Product",
    status: "available",
    image_url: "https://example.com/images/phone.jpg",
    estimated_value: 200.0,
    created_at: "2024-10-05T14:00:00Z",
  },
  {
    user_id: 6,
    title: "Laptop Repair",
    description: "Expert laptop repair services, includes diagnostics.",
    category: "Service",
    status: "available",
    image_url: "https://example.com/images/laptoprepair.jpg",
    estimated_value: 150.0,
    created_at: "2024-10-06T09:45:00Z",
  },
  {
    user_id: 7,
    title: "Sofa Set",
    description: "Large sofa set, 3-seater and 2-seater, lightly used.",
    category: "Product",
    status: "available",
    image_url: "https://example.com/images/sofa.jpg",
    estimated_value: 400.0,
    created_at: "2024-10-07T12:30:00Z",
  },
  {
    user_id: 8,
    title: "Cooking Classes",
    description: "Learn to cook gourmet meals from a professional chef.",
    category: "Service",
    status: "available",
    image_url: "https://example.com/images/cooking.jpg",
    estimated_value: 100.0,
    created_at: "2024-10-08T15:00:00Z",
  },
  {
    user_id: 9,
    title: "Electric Scooter",
    description: "Electric scooter, like new, perfect for city commuting.",
    category: "Product",
    status: "available",
    image_url: "https://example.com/images/scooter.jpg",
    estimated_value: 250.0,
    created_at: "2024-10-09T10:15:00Z",
  },
  {
    user_id: 10,
    title: "Language Lessons",
    description: "Online lessons for learning Spanish.",
    category: "Service",
    status: "available",
    image_url: "https://example.com/images/spanish.jpg",
    estimated_value: 50.0,
    created_at: "2024-10-10T11:00:00Z",
  },
  {
    user_id: 11,
    title: "Gaming Console",
    description: "Gaming console with two controllers and 5 games.",
    category: "Product",
    status: "available",
    image_url: "https://example.com/images/console.jpg",
    estimated_value: 300.0,
    created_at: "2024-10-11T13:00:00Z",
  },
  {
    user_id: 12,
    title: "Photography Service",
    description: "Professional photography service for events.",
    category: "Service",
    status: "available",
    image_url: "https://example.com/images/photography.jpg",
    estimated_value: 500.0,
    created_at: "2024-10-12T12:00:00Z",
  },
  {
    user_id: 13,
    title: "Dining Table",
    description: "Wooden dining table, seats six people.",
    category: "Product",
    status: "available",
    image_url: "https://example.com/images/table.jpg",
    estimated_value: 350.0,
    created_at: "2024-10-12T14:00:00Z",
  },
  {
    user_id: 14,
    title: "Math Tutoring",
    description: "Expert tutoring in mathematics for high school students.",
    category: "Service",
    status: "available",
    image_url: "https://example.com/images/math.jpg",
    estimated_value: 40.0,
    created_at: "2024-10-13T09:00:00Z",
  },
  {
    user_id: 15,
    title: "Television",
    description: "42-inch flat-screen TV, works perfectly.",
    category: "Product",
    status: "available",
    image_url: "https://example.com/images/tv.jpg",
    estimated_value: 250.0,
    created_at: "2024-10-14T08:00:00Z",
  },
  {
    user_id: 16,
    title: "Fitness Training",
    description: "Personal fitness training sessions.",
    category: "Service",
    status: "available",
    image_url: "https://example.com/images/fitness.jpg",
    estimated_value: 100.0,
    created_at: "2024-10-15T11:45:00Z",
  },
  {
    user_id: 17,
    title: "Dining Chairs",
    description: "Set of 4 dining chairs, modern design.",
    category: "Product",
    status: "available",
    image_url: "https://example.com/images/chairs.jpg",
    estimated_value: 150.0,
    created_at: "2024-10-16T10:30:00Z",
  },
  {
    user_id: 18,
    title: "House Painting Service",
    description: "Professional house painting, includes materials.",
    category: "Service",
    status: "available",
    image_url: "https://example.com/images/painting.jpg",
    estimated_value: 700.0,
    created_at: "2024-10-17T09:00:00Z",
  },
  {
    user_id: 19,
    title: "Electric Guitar",
    description: "Electric guitar with amp, lightly used.",
    category: "Product",
    status: "available",
    image_url: "https://example.com/images/guitar2.jpg",
    estimated_value: 400.0,
    created_at: "2024-10-18T12:15:00Z",
  },
  {
    user_id: 20,
    title: "Website Design",
    description: "Custom website design and development services.",
    category: "Service",
    status: "available",
    image_url: "https://example.com/images/webdesign.jpg",
    estimated_value: 1200.0,
    created_at: "2024-10-19T10:30:00Z",
  },
  {
    user_id: 21,
    title: "Blender",
    description: "High-powered blender, perfect for smoothies.",
    category: "Product",
    status: "available",
    image_url: "https://example.com/images/blender.jpg",
    estimated_value: 100.0,
    created_at: "2024-10-20T11:00:00Z",
  },
  {
    user_id: 22,
    title: "Pet Sitting",
    description: "Professional pet sitting service for dogs and cats.",
    category: "Service",
    status: "available",
    image_url: "https://example.com/images/petsitting.jpg",
    estimated_value: 50.0,
    created_at: "2024-10-21T12:30:00Z",
  },
  {
    user_id: 23,
    title: "Bicycle Repair",
    description: "Bicycle repair and maintenance service.",
    category: "Service",
    status: "available",
    image_url: "https://example.com/images/bikerepair.jpg",
    estimated_value: 70.0,
    created_at: "2024-10-22T09:00:00Z",
  },
  {
    user_id: 24,
    title: "Bookshelf",
    description: "Tall wooden bookshelf, excellent condition.",
    category: "Product",
    status: "available",
    image_url: "https://example.com/images/bookshelf.jpg",
    estimated_value: 80.0,
    created_at: "2024-10-23T11:00:00Z",
  },
  {
    user_id: 25,
    title: "Language Translation",
    description: "Professional translation services for documents.",
    category: "Service",
    status: "available",
    image_url: "https://example.com/images/translation.jpg",
    estimated_value: 200.0,
    created_at: "2024-10-24T08:30:00Z",
  },
  {
    user_id: 26,
    title: "Laptop",
    description: "Slightly used laptop, 16GB RAM, 256GB SSD.",
    category: "Product",
    status: "available",
    image_url: "https://example.com/images/laptop.jpg",
    estimated_value: 800.0,
    created_at: "2024-10-25T14:00:00Z",
  },
  {
    user_id: 27,
    title: "Digital Marketing Services",
    description: "Comprehensive digital marketing services to grow your brand.",
    category: "Service",
    status: "available",
    image_url: "https://example.com/images/marketing.jpg",
    estimated_value: 1000.0,
    created_at: "2024-10-26T09:00:00Z",
  },
  {
    user_id: 28,
    title: "Coffee Grinder",
    description: "High-quality coffee grinder, excellent for home brewing.",
    category: "Product",
    status: "available",
    image_url: "https://example.com/images/coffegrinder.jpg",
    estimated_value: 75.0,
    created_at: "2024-10-27T10:30:00Z",
  },
  {
    user_id: 29,
    title: "Graphic Design Services",
    description: "Custom graphic design for logos, brochures, and more.",
    category: "Service",
    status: "available",
    image_url: "https://example.com/images/graphicdesign.jpg",
    estimated_value: 500.0,
    created_at: "2024-10-28T11:15:00Z",
  },
  {
    user_id: 30,
    title: "Drill Set",
    description: "Professional-grade drill set, lightly used.",
    category: "Product",
    status: "available",
    image_url: "https://example.com/images/drill.jpg",
    estimated_value: 120.0,
    created_at: "2024-10-29T08:30:00Z",
  },
  {
    user_id: 31,
    title: "Pet Grooming Services",
    description: "Full-service grooming for dogs and cats.",
    category: "Service",
    status: "available",
    image_url: "https://example.com/images/petgrooming.jpg",
    estimated_value: 60.0,
    created_at: "2024-10-30T09:45:00Z",
  },
  {
    user_id: 32,
    title: "Sewing Machine",
    description: "Used sewing machine in great condition.",
    category: "Product",
    status: "available",
    image_url: "https://example.com/images/sewingmachine.jpg",
    estimated_value: 200.0,
    created_at: "2024-10-31T10:00:00Z",
  },
  {
    user_id: 33,
    title: "Personal Chef Services",
    description: "On-demand personal chef for events or weekly meals.",
    category: "Service",
    status: "available",
    image_url: "https://example.com/images/chef.jpg",
    estimated_value: 300.0,
    created_at: "2024-11-01T12:00:00Z",
  },
  {
    user_id: 34,
    title: "Baby Crib",
    description: "Baby crib in excellent condition, includes mattress.",
    category: "Product",
    status: "available",
    image_url: "https://example.com/images/babycrib.jpg",
    estimated_value: 150.0,
    created_at: "2024-11-02T11:15:00Z",
  },
  {
    user_id: 35,
    title: "Painting Lessons",
    description: "Learn painting techniques with a professional artist.",
    category: "Service",
    status: "available",
    image_url: "https://example.com/images/paintinglessons.jpg",
    estimated_value: 75.0,
    created_at: "2024-11-03T14:00:00Z",
  },
  {
    user_id: 36,
    title: "Digital Camera",
    description:
      "High-quality digital camera, 20MP, excellent for photography.",
    category: "Product",
    status: "available",
    image_url: "https://example.com/images/camera.jpg",
    estimated_value: 400.0,
    created_at: "2024-11-04T09:30:00Z",
  },
  {
    user_id: 37,
    title: "Guitar Amplifier",
    description: "Guitar amplifier, 50 watts, works perfectly.",
    category: "Product",
    status: "available",
    image_url: "https://example.com/images/amplifier.jpg",
    estimated_value: 250.0,
    created_at: "2024-11-05T10:15:00Z",
  },
  {
    user_id: 38,
    title: "Event Planning Services",
    description:
      "Professional event planning services for weddings and parties.",
    category: "Service",
    status: "available",
    image_url: "https://example.com/images/eventplanning.jpg",
    estimated_value: 700.0,
    created_at: "2024-11-06T08:45:00Z",
  },
  {
    user_id: 39,
    title: "Lawn Mower",
    description: "Electric lawn mower, lightly used, great condition.",
    category: "Product",
    status: "available",
    image_url: "https://example.com/images/lawnmower.jpg",
    estimated_value: 250.0,
    created_at: "2024-11-07T10:30:00Z",
  },
  {
    user_id: 40,
    title: "Fitness Equipment",
    description: "Set of dumbbells, resistance bands, and workout mat.",
    category: "Product",
    status: "available",
    image_url: "https://example.com/images/fitnessequipment.jpg",
    estimated_value: 150.0,
    created_at: "2024-11-08T12:15:00Z",
  },
  {
    user_id: 41,
    title: "Legal Consulting Services",
    description: "Professional legal consulting for small businesses.",
    category: "Service",
    status: "available",
    image_url: "https://example.com/images/legal.jpg",
    estimated_value: 1000.0,
    created_at: "2024-11-09T14:00:00Z",
  },
  {
    user_id: 42,
    title: "Massage Chair",
    description: "Full-body massage chair, like new condition.",
    category: "Product",
    status: "available",
    image_url: "https://example.com/images/massagechair.jpg",
    estimated_value: 600.0,
    created_at: "2024-11-10T08:30:00Z",
  },
  {
    user_id: 43,
    title: "Home Cleaning Service",
    description: "Full-service home cleaning, includes deep cleaning.",
    category: "Service",
    status: "available",
    image_url: "https://example.com/images/cleaning.jpg",
    estimated_value: 200.0,
    created_at: "2024-11-11T10:00:00Z",
  },
  {
    user_id: 44,
    title: "Barbecue Grill",
    description: "Gas barbecue grill, excellent for outdoor cooking.",
    category: "Product",
    status: "available",
    image_url: "https://example.com/images/grill.jpg",
    estimated_value: 300.0,
    created_at: "2024-11-12T11:30:00Z",
  },
  {
    user_id: 45,
    title: "Home Theater System",
    description: "5.1 surround sound home theater system, includes speakers.",
    category: "Product",
    status: "available",
    image_url: "https://example.com/images/hometheater.jpg",
    estimated_value: 500.0,
    created_at: "2024-11-13T13:00:00Z",
  },
  {
    user_id: 46,
    title: "Photography Editing Services",
    description:
      "Professional photo editing services for events and portraits.",
    category: "Service",
    status: "available",
    image_url: "https://example.com/images/photoediting.jpg",
    estimated_value: 150.0,
    created_at: "2024-11-14T14:15:00Z",
  },
  {
    user_id: 47,
    title: "Office Desk",
    description: "Large wooden office desk, lightly used, great condition.",
    category: "Product",
    status: "available",
    image_url: "https://example.com/images/officedesk.jpg",
    estimated_value: 200.0,
    created_at: "2024-11-15T09:30:00Z",
  },
  {
    user_id: 48,
    title: "Home Renovation Services",
    description:
      "Full-service home renovation for kitchens, bathrooms, and more.",
    category: "Service",
    status: "available",
    image_url: "https://example.com/images/renovation.jpg",
    estimated_value: 3000.0,
    created_at: "2024-11-16T10:45:00Z",
  },
  {
    user_id: 49,
    title: "Baby Stroller",
    description: "Lightweight baby stroller, excellent condition.",
    category: "Product",
    status: "available",
    image_url: "https://example.com/images/babystroller.jpg",
    estimated_value: 180.0,
    created_at: "2024-11-17T11:00:00Z",
  },
  {
    user_id: 50,
    title: "Car Detailing Service",
    description:
      "Full-service car detailing, includes waxing and interior cleaning.",
    category: "Service",
    status: "available",
    image_url: "https://example.com/images/cardetailing.jpg",
    estimated_value: 250.0,
    created_at: "2024-11-18T12:30:00Z",
  },
];

export const messagesData = [
  {
    id: 1,
    sender_id: 1,
    recipient_id: 2,
    content: "Hey, are you still offering the mountain bike?",
    sent_at: "2024-10-12T10:05:00",
  },
  {
    id: 2,
    sender_id: 2,
    recipient_id: 1,
    content: "Yes, it's still available. Are you interested?",
    sent_at: "2024-10-12T10:07:00",
  },
  {
    id: 3,
    sender_id: 1,
    recipient_id: 2,
    content: "I am! Can we negotiate the price?",
    sent_at: "2024-10-12T10:10:00",
  },
  {
    id: 4,
    sender_id: 2,
    recipient_id: 1,
    content: "Sure, what's your offer?",
    sent_at: "2024-10-12T10:12:00",
  },
  {
    id: 5,
    sender_id: 1,
    recipient_id: 2,
    content: "How about $250?",
    sent_at: "2024-10-12T10:14:00",
  },
  {
    id: 6,
    sender_id: 3,
    recipient_id: 4,
    content:
      "Hi, I saw your post about guitar lessons. Are you still taking students?",
    sent_at: "2024-10-12T11:00:00",
  },
  {
    id: 7,
    sender_id: 4,
    recipient_id: 3,
    content: "Yes, I am! Would you like to book a lesson?",
    sent_at: "2024-10-12T11:02:00",
  },
  {
    id: 8,
    sender_id: 3,
    recipient_id: 4,
    content: "I'd like to. How much do you charge per lesson?",
    sent_at: "2024-10-12T11:05:00",
  },
  {
    id: 9,
    sender_id: 4,
    recipient_id: 3,
    content: "I charge $40 per hour.",
    sent_at: "2024-10-12T11:07:00",
  },
  {
    id: 10,
    sender_id: 3,
    recipient_id: 4,
    content: "Sounds good! Can I book a lesson for this weekend?",
    sent_at: "2024-10-12T11:10:00",
  },
  {
    id: 11,
    sender_id: 5,
    recipient_id: 6,
    content: "Is the coffee maker still available?",
    sent_at: "2024-10-12T09:15:00",
  },
  {
    id: 12,
    sender_id: 6,
    recipient_id: 5,
    content: "Yes, it is. Would you like to come check it out?",
    sent_at: "2024-10-12T09:17:00",
  },
  {
    id: 13,
    sender_id: 5,
    recipient_id: 6,
    content: "Sure, when can I stop by?",
    sent_at: "2024-10-12T09:19:00",
  },
  {
    id: 14,
    sender_id: 6,
    recipient_id: 5,
    content: "How about tomorrow afternoon?",
    sent_at: "2024-10-12T09:22:00",
  },
  {
    id: 15,
    sender_id: 5,
    recipient_id: 6,
    content: "That works for me! I'll see you then.",
    sent_at: "2024-10-12T09:25:00",
  },
  {
    id: 16,
    sender_id: 7,
    recipient_id: 8,
    content:
      "Hey, I saw your ad for the yoga classes. Are they still available?",
    sent_at: "2024-10-12T08:50:00",
  },
  {
    id: 17,
    sender_id: 8,
    recipient_id: 7,
    content: "Yes, I'm still offering classes. Would you like to join?",
    sent_at: "2024-10-12T08:53:00",
  },
  {
    id: 18,
    sender_id: 7,
    recipient_id: 8,
    content: "I would love to! When do the classes take place?",
    sent_at: "2024-10-12T08:55:00",
  },
  {
    id: 19,
    sender_id: 8,
    recipient_id: 7,
    content: "Classes are every Saturday at 10 AM.",
    sent_at: "2024-10-12T08:57:00",
  },
  {
    id: 20,
    sender_id: 7,
    recipient_id: 8,
    content: "Great! Sign me up for this weekend's session.",
    sent_at: "2024-10-12T09:00:00",
  },
  {
    id: 21,
    sender_id: 9,
    recipient_id: 10,
    content:
      "I'm interested in the smartphone you posted. Is it still available?",
    sent_at: "2024-10-12T07:30:00",
  },
  {
    id: 22,
    sender_id: 10,
    recipient_id: 9,
    content: "Yes, it's still available. Are you looking to buy?",
    sent_at: "2024-10-12T07:32:00",
  },
  {
    id: 23,
    sender_id: 9,
    recipient_id: 10,
    content: "Yes, I'd like to know more about the condition.",
    sent_at: "2024-10-12T07:35:00",
  },
  {
    id: 24,
    sender_id: 10,
    recipient_id: 9,
    content: "It's in good condition, only minor scratches on the screen.",
    sent_at: "2024-10-12T07:37:00",
  },
  {
    id: 25,
    sender_id: 9,
    recipient_id: 10,
    content: "Great! When can I come take a look?",
    sent_at: "2024-10-12T07:40:00",
  },
  {
    id: 26,
    sender_id: 11,
    recipient_id: 12,
    content: "Hi, I saw your ad for laptop repair. How much do you charge?",
    sent_at: "2024-10-12T06:45:00",
  },
  {
    id: 27,
    sender_id: 12,
    recipient_id: 11,
    content: "I charge $150 for diagnostics and repairs.",
    sent_at: "2024-10-12T06:47:00",
  },
  {
    id: 28,
    sender_id: 11,
    recipient_id: 12,
    content: "That's reasonable. Can I bring my laptop in today?",
    sent_at: "2024-10-12T06:50:00",
  },
  {
    id: 29,
    sender_id: 12,
    recipient_id: 11,
    content: "Yes, feel free to stop by anytime after 1 PM.",
    sent_at: "2024-10-12T06:52:00",
  },
  {
    id: 30,
    sender_id: 11,
    recipient_id: 12,
    content: "Great! I'll be there.",
    sent_at: "2024-10-12T06:55:00",
  },
  {
    id: 31,
    sender_id: 13,
    recipient_id: 14,
    content: "Hey, I'm interested in the sofa set. Is it still available?",
    sent_at: "2024-10-12T05:20:00",
  },
  {
    id: 32,
    sender_id: 14,
    recipient_id: 13,
    content: "Yes, the set is still available.",
    sent_at: "2024-10-12T05:22:00",
  },
  {
    id: 33,
    sender_id: 13,
    recipient_id: 14,
    content: "How much are you asking for it?",
    sent_at: "2024-10-12T05:24:00",
  },
  {
    id: 34,
    sender_id: 14,
    recipient_id: 13,
    content: "I'm asking for $400. It's in great condition.",
    sent_at: "2024-10-12T05:26:00",
  },
  {
    id: 35,
    sender_id: 13,
    recipient_id: 14,
    content: "Can I come by and take a look?",
    sent_at: "2024-10-12T05:28:00",
  },
  {
    id: 36,
    sender_id: 14,
    recipient_id: 13,
    content: "Sure! How about tomorrow at noon?",
    sent_at: "2024-10-12T05:30:00",
  },
  {
    id: 37,
    sender_id: 13,
    recipient_id: 14,
    content: "That works for me. See you then!",
    sent_at: "2024-10-12T05:32:00",
  },
  {
    id: 38,
    sender_id: 15,
    recipient_id: 16,
    content: "Hey, do you still have that blender for sale?",
    sent_at: "2024-10-12T04:15:00",
  },
  {
    id: 39,
    sender_id: 16,
    recipient_id: 15,
    content: "Yes, it's still available!",
    sent_at: "2024-10-12T04:17:00",
  },
  {
    id: 40,
    sender_id: 15,
    recipient_id: 16,
    content: "Cool, I’m interested. Can you do $80?",
    sent_at: "2024-10-12T04:19:00",
  },
  {
    id: 41,
    sender_id: 16,
    recipient_id: 15,
    content: "How about $90? It's almost new.",
    sent_at: "2024-10-12T04:21:00",
  },
  {
    id: 42,
    sender_id: 15,
    recipient_id: 16,
    content: "Alright, I’ll take it. Can I pick it up tomorrow?",
    sent_at: "2024-10-12T04:23:00",
  },
  {
    id: 43,
    sender_id: 17,
    recipient_id: 18,
    content: "Is your gaming console still available?",
    sent_at: "2024-10-12T03:00:00",
  },
  {
    id: 44,
    sender_id: 18,
    recipient_id: 17,
    content: "Yes, it is. Are you interested?",
    sent_at: "2024-10-12T03:02:00",
  },
  {
    id: 45,
    sender_id: 17,
    recipient_id: 18,
    content: "Definitely! Can I come pick it up this evening?",
    sent_at: "2024-10-12T03:05:00",
  },
  {
    id: 46,
    sender_id: 18,
    recipient_id: 17,
    content: "That works for me. Does 6 PM sound good?",
    sent_at: "2024-10-12T03:07:00",
  },
  {
    id: 47,
    sender_id: 17,
    recipient_id: 18,
    content: "Perfect! I'll see you then.",
    sent_at: "2024-10-12T03:10:00",
  },
  {
    id: 48,
    sender_id: 19,
    recipient_id: 20,
    content: "Hey, are you still offering the web design services?",
    sent_at: "2024-10-12T02:45:00",
  },
  {
    id: 49,
    sender_id: 20,
    recipient_id: 19,
    content: "Yes, I am! Do you need help with a website?",
    sent_at: "2024-10-12T02:47:00",
  },
  {
    id: 50,
    sender_id: 19,
    recipient_id: 20,
    content:
      "Yes, I'm looking to revamp my business site. Can we discuss details?",
    sent_at: "2024-10-12T02:50:00",
  },
];

export const tradesData = [
  {
    id: 1,
    offer_id_1: 1,
    offer_id_2: 2,
    status: "completed",
    created_at: "2024-10-10T09:00:00",
  },
  {
    id: 2,
    offer_id_1: 3,
    offer_id_2: 4,
    status: "in process",
    created_at: "2024-10-10T10:30:00",
  },
  {
    id: 3,
    offer_id_1: 5,
    offer_id_2: 6,
    status: "completed",
    created_at: "2024-10-11T11:15:00",
  },
  {
    id: 4,
    offer_id_1: 7,
    offer_id_2: 8,
    status: "pending",
    created_at: "2024-10-11T12:00:00",
  },
  {
    id: 5,
    offer_id_1: 9,
    offer_id_2: 10,
    status: "completed",
    created_at: "2024-10-11T13:45:00",
  },
  {
    id: 6,
    offer_id_1: 11,
    offer_id_2: 12,
    status: "in process",
    created_at: "2024-10-12T14:30:00",
  },
  {
    id: 7,
    offer_id_1: 13,
    offer_id_2: 14,
    status: "pending",
    created_at: "2024-10-12T15:00:00",
  },
  {
    id: 8,
    offer_id_1: 15,
    offer_id_2: 16,
    status: "completed",
    created_at: "2024-10-12T16:10:00",
  },
  {
    id: 9,
    offer_id_1: 17,
    offer_id_2: 18,
    status: "pending",
    created_at: "2024-10-13T08:45:00",
  },
  {
    id: 10,
    offer_id_1: 19,
    offer_id_2: 20,
    status: "in process",
    created_at: "2024-10-13T09:30:00",
  },
];
