export const studentsData = [
  { name: "יונתן כהן", grade: "יא", math_units: 5 },
  { name: "תמר לוי", grade: "יב", math_units: 4 },
  { name: "נועה ישראלי", grade: "יא", math_units: 5 },
  { name: "דניאל מזרחי", grade: "יב", math_units: 3 },
  { name: "ליאן בן חמו", grade: "י", math_units: 5 },
  { name: "איתי גל", grade: "י", math_units: 4 },
  { name: "רוני חן", grade: "יב", math_units: 5 },
  { name: "שירה ישראלי", grade: "י", math_units: 3 },
  { name: "רון לוי", grade: "יא", math_units: 4 },
  { name: "מיכל שחר", grade: "י", math_units: 5 },
  { name: "טל כהן", grade: "יב", math_units: 5 },
  { name: "דנה אביטל", grade: "יא", math_units: 3 },
  { name: "עדי ברק", grade: "י", math_units: 4 },
  { name: "עומר ברנשטיין", grade: "יא", math_units: 5 },
  { name: "שני קפלן", grade: "י", math_units: 3 },
  { name: "לירון קוגן", grade: "י", math_units: 4 },
  { name: "רינת דוידי", grade: "י", math_units: 5 },
  { name: "יובל יעקב", grade: "יא", math_units: 5 },
  { name: "רועי רונן", grade: "יב", math_units: 4 },
  { name: "יעל מזרחי", grade: "י", math_units: 3 },
  { name: "אורן לוי", grade: "יא", math_units: 4 },
  { name: "שחר מימון", grade: "יב", math_units: 5 },
  { name: "מור עזרא", grade: "י", math_units: 5 },
  { name: "דנה כהן", grade: "י", math_units: 4 },
  { name: "עדי נגר", grade: "יא", math_units: 3 },
  { name: "עומר ישראלי", grade: "י", math_units: 5 },
  { name: "איתי ברק", grade: "יב", math_units: 5 },
  { name: "שיר בן צבי", grade: "יא", math_units: 4 },
  { name: "יובל דוידי", grade: "י", math_units: 3 },
  { name: "רז ישראלי", grade: "י", math_units: 4 },
  { name: "אור דוידי", grade: "יב", math_units: 5 },
  { name: "עדי גל", grade: "יא", math_units: 4 },
  { name: "ליאן כהן", grade: "י", math_units: 3 },
  { name: "תומר מזרחי", grade: "יא", math_units: 5 },
  { name: "נועה שחר", grade: "י", math_units: 5 },
  { name: "רינת רונן", grade: "יב", math_units: 4 },
  { name: "שירה כהן", grade: "יא", math_units: 5 },
  { name: "עומר לוי", grade: "י", math_units: 3 },
  { name: "יואב מימון", grade: "יב", math_units: 5 },
  { name: "ענת ישראלי", grade: "יא", math_units: 4 },
  { name: "שחר כהן", grade: "י", math_units: 5 },
  { name: "אלעד בן חמו", grade: "יב", math_units: 3 },
  { name: "רונית לוי", grade: "י", math_units: 4 },
  { name: "ליאת ישראלי", grade: "יא", math_units: 5 },
  { name: "אלון דוידי", grade: "יב", math_units: 5 },
  { name: "איתי כהן", grade: "יא", math_units: 3 },
  { name: "עומר מזרחי", grade: "י", math_units: 5 },
  { name: "רועי כהן", grade: "יב", math_units: 4 },
  { name: "יעל ברק", grade: "יא", math_units: 3 },
  { name: "יובל לוי", grade: "י", math_units: 5 },
  { name: "שני ישראלי", grade: "יב", math_units: 4 },
  { name: "דניאל כהן", grade: "י", math_units: 3 },
  { name: "לירון בן חמו", grade: "יא", math_units: 5 },
  { name: "שחר לוי", grade: "יב", math_units: 4 },
  { name: "עדי ישראלי", grade: "יא", math_units: 3 },
  { name: "יואב כהן", grade: "י", math_units: 5 },
  { name: "נועה לוי", grade: "יא", math_units: 4 },
  { name: "אלעד ברק", grade: "יב", math_units: 5 },
  { name: "עומר כהן", grade: "י", math_units: 3 },
  { name: "יובל רונן", grade: "יא", math_units: 5 },
  { name: "מור מזרחי", grade: "יב", math_units: 4 },
  { name: "שירה ברק", grade: "יא", math_units: 3 },
  { name: "רז כהן", grade: "י", math_units: 5 },
  { name: "שני לוי", grade: "יא", math_units: 4 },
  { name: "יובל מזרחי", grade: "יב", math_units: 3 },
  { name: "נועה כהן", grade: "י", math_units: 5 },
  { name: "רינת ברק", grade: "יא", math_units: 4 },
  { name: "עומר רונן", grade: "יב", math_units: 5 },
  { name: "ליאת כהן", grade: "י", math_units: 3 },
  { name: "יואב ישראלי", grade: "יא", math_units: 4 },
  { name: "דניאל לוי", grade: "י", math_units: 5 },
  { name: "נועה ברק", grade: "יב", math_units: 3 },
  { name: "שחר כהן", grade: "יא", math_units: 5 },
  { name: "יובל לוי", grade: "י", math_units: 4 },
  { name: "עדי מזרחי", grade: "יא", math_units: 3 },
  { name: "מור כהן", grade: "י", math_units: 5 },
  { name: "שירה לוי", grade: "יא", math_units: 4 },
  { name: "עומר כהן", grade: "יב", math_units: 3 },
  { name: "אלעד ישראלי", grade: "י", math_units: 5 },
  { name: "רועי ברק", grade: "יא", math_units: 4 },
  { name: "ליאן כהן", grade: "יב", math_units: 5 },
  { name: "דניאל ישראלי", grade: "י", math_units: 3 },
  { name: "שחר כהן", grade: "יא", math_units: 4 },
  { name: "נועה לוי", grade: "י", math_units: 5 },
  { name: "רז ברק", grade: "יא", math_units: 3 },
  { name: "יואב כהן", grade: "י", math_units: 5 },
  { name: "עומר לוי", grade: "יב", math_units: 4 },
  { name: "יובל ברק", grade: "י", math_units: 3 },
];

export const schoolsData = [
  { name: "תיכון עירוני א'", city: "תל אביב" },
  { name: "תיכון עירוני ג'", city: "חיפה" },
  { name: "תיכון חדש", city: "ירושלים" },
  { name: "תיכון רוטברג", city: "רמת השרון" },
  { name: "תיכון דרור", city: "הרצליה" },
];
